### ISSUE TITLE
ANE file not included?

### ISSUE THREAD

**Issue by harry248** [testfairy/testfairy-ane#1]
Just downloaded the repository but the ANE file does not seem to be included?

**Comment by sgavalas** [comment]
Same problem there is no ANE file.

**Comment by aeyachts99** [comment]
And me.. no ANE included.

**Comment by gmegidish** [comment]
Hey all,

Here's a link to version 1.4.4. ANE will soon appear on the download page for app.
https://app.testfairy.com/sdk/TestFairySDK-1.4.4.ane

**Comment by bjeld** [comment]
thank you :)
