### ISSUE TITLE
Impossible to build iOS AIR app since 2.1.1

### ISSUE THREAD

**Issue by mr-mmmmore** [testfairy/testfairy-ane#11]
I have just updated my app to the TestFairy SDK 2.1.1 and I can't build anymore, I get this message (in IntellijIdea): "Object file xxx was built for a newer iOS version (8.1) than being linked (7.0)".

![image](https://user-images.githubusercontent.com/14160945/27094201-9c94d312-5069-11e7-9d0e-28ee06230b5e.png)

I am using XCode 8.1 and AIR SDK 25.

**Comment by vijaysharm** [comment]
Hello @mr-mmmmore I dont see an error, i only see warnings, can you clarify where the error is?

**Comment by mr-mmmmore** [comment]
After this the app is not built.

**Comment by vijaysharm** [comment]
A warning should not stop your app from building. this is just a warning saying that we've raised the minimum iOS requirement to 8.1. You can either raise your app's minimum to match this version, or you can turn off any options that stop your build from ending on warning.

**Comment by mr-mmmmore** [comment]
When building in IntellijIdea it does stop the build. So I've raised the app's OS minimum version. 
Thanks

**Comment by rozd** [comment]
@mr-mmmmore try to package your application from command-line, it seems your error is down of the list after all warnings, or in case you can find a way to see full log directly from IDEA interface please share it with me.

**Comment by mr-mmmmore** [comment]
Thanks @rozd, but raising the minimum iOS version was fine for this app so the problem is solved now.
