### ISSUE TITLE
Begin method does not accept any params

### ISSUE THREAD

**Issue by bjeld** [testfairy/testfairy-ane#3]
It seems that begin method does not accept any params. 
AirTestFairy.begin(APP_TOKEN);

Im using the Ane linked here - https://app.testfairy.com/ios-sdk/TestFairySDK-1.4.4.ane
Maybe it just need to be recompiled after the latest changes.

**Comment by gmegidish** [comment]
Hey @bjeld, we were in the middle of a serious commit :)

Can you please download the ANE again from: 
https://s3.amazonaws.com/testfairy/sdk/TestFairySDK-1.4.4.ane 

It should now work, begin accepts the app token as described in the readme. Previously it would use the configuration from the -app.xml file, but that proved annoying for some :)

**Comment by bjeld** [comment]
Hi.
Begin now accepts the app token. Thanks.
Im not seeing any sessions counts in the Testfairy Dashboard though.

**Comment by gmegidish** [comment]
Can you please make sure you're using the app token and not the api key from your settings page?
If everything seems okay, please send an email to support@testfairy.com and they will take really good care of you :)
