### ISSUE TITLE
No Mention of ExtensionId

### ISSUE THREAD

**Issue by JimTheMan** [testfairy/testfairy-ane#6]
Building the project according to the incomplete documentation gives this:

The content cannot be loaded because there was a problem loading an extension: Error: Requested extension com.testfairy.AirTestFairy could not be found.

In the descriptor xml, you need a  line <extensionId></extesionId> which is some mysterious id that is hidden from the public.

**Comment by gmegidish** [comment]
Hey Jim,

Can you please try com.testfairy as the extension id? (as in: https://github.com/testfairy/testfairy-ane/blob/master/flex/AirTestFairy/src/com/testfairy/extension.xml)

Also, how are you building this? Which Adobe tool are you using? Which platforms are you targeting?

**Comment by Xgamefactory** [comment]
You should add this to docs.
https://docs.testfairy.com/Platforms/Adobe_Air.html

**Comment by vijaysharm** [comment]
@Xgamefactory done!
