### ISSUE TITLE
Missed library?

### ISSUE THREAD

**Issue by Diamanter** [testfairy/testfairy-ane#8]
I tried AIR 18 and AIR 20.

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_WKWebView", referenced from:
      objc-class-ref in C:\Users\Denis\AppData\Local\Temp\49d48539-81ab-46d0-ade9-76435887bbec\libcom.testfairy.a(TestFairy.o)
ld: symbol(s) not found for architecture arm64
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_WKWebView", referenced from:
      objc-class-ref in C:\Users\Denis\AppData\Local\Temp\49d48539-81ab-46d0-ade9-76435887bbec\libcom.testfairy.a(TestFairy.o)
ld: symbol(s) not found for architecture armv7

**Comment by gmegidish** [comment]
Hey @Diamanter 

We just released SDK 1.6.4. It seems that 1.6.2 required WKWebKit. So you may either upgrade to 1.6.4, or add WKWebKit.framework and it'll work as expected.

Thank you for the bug report!!
