### ISSUE TITLE
log and screenshots recording command not working when using ANE

### ISSUE THREAD

**Issue by SlavomirDurej** [testfairy/testfairy-ane#9]
I've added all the required tags in the manifest.xml and added .begin command to my app 

AirTestFairy.begin(TEST_FAIRY_APP_TOKEN);

then later on , I wanted to use AirTestFairy.log("Some string"); so I can see custom traces in the Aplication logs, but nothing is showing up.

Also when I don't add the ANE, (and you inject your wrapper app)  I can see the screenshot captured (every 1s) but with the ANE they're not..

**Comment by giltsl** [comment]
Hi @SlavomirDurej, 
We are checking it right now.

@vijaysharm can you please look into the `AirTestFairy.log()` issue?

**Comment by vijaysharm** [comment]
Hi @SlavomirDurej thanks for pointing this out. I'm assuming log wasn't working on Android? I just submitted a patch to fix log, it should be in the next release (maybe end of day, or early next week). 

As for takescreenshot, we're currently still trying to figure out how to do that on Android (it works on iOS). So although the interface is there for AdobeAir, we're still trying to figure it out on Android.

Based on issue #10, were you able to actually run the ANE  if you were able to observe the failure to log?

**Comment by SlavomirDurej** [comment]
Yes log (and screenshots) wasn't working on Android. 

I was able to build it with ANE, but this project uses about 4-5 different (other third party) ANEs and has additional tags in application.xml.  It's maybe those other ANE's or combination of them that makes it work, not sure. 

However, I think ANE should work without those as well..

**Comment by vijaysharm** [comment]
@SlavomirDurej Great. I'll mark this issue as closed, and we can continue the discussion in the other issue. I'm interested in knowing what those other ANEs are (to help with my investigation)

**Comment by SlavomirDurej** [comment]
I don't quite understand why you close this issue, normaly users would verify this issue is fixed in the next release? 
Or do you already have a new version of ANE that has .log() and screenshoting issue fixed that you've yourself tested and are 100% sure it works?

**Comment by vijaysharm** [comment]
The fix for log is available here https://github.com/testfairy/testfairy-ane/commit/6b38dda286fe4245f5b4ad2f8adcbb49add82946 which i tested. However, we can keep this issue open if you want to track it. Otherwise, people tend to track the release (which is forth coming). 

We can create a new issue if you'd like to track the screenshot issue, however, as I mentioned, this is something that is not available on Android.

**Comment by SlavomirDurej** [comment]
> something that is not available on Android

It works when I don't include the SDK though? On Android as well.

**Comment by vijaysharm** [comment]
I'm sorry @SlavomirDurej I don't think I understand what you're saying. What I'm trying to say is, the takeScreenShot call in AirTestFairy is a no-op on Android.

What I'm not understanding is what you mean when you say "it works when I don't include the SDK". Are you saying that you're able to take screenshots with AirTestFairy without the SDK?

**Comment by vijaysharm** [comment]
Maybe you can explain to me what "and you inject your wrapper app" means? I'm not familiar with what that means?

**Comment by SlavomirDurej** [comment]
What I mean is,  if I don't include the ANE/SKD in my apk and upload the .apk file via the TestFairy web upload button on dashboard , I can see the screenshots appearing. 
I'm assuming you're wrapping the apk into another app ("testfairy wrapper") that provides this functionality.

**Comment by vijaysharm** [comment]
Ah, ok. So our "wrapper app" does things that our SDK cannot yet. However, we're transitioning away from the wrapper app approach for various reasons. We're aiming to add screenshot support in the near future, but we're still trying to figure out how to do that.

Again, if you'd like to open a separate issue regarding that, then please feel free to do so.

**Comment by bluntcoder** [comment]
Is it possible to still use the TestFairy Wrapper app and both Android and iOS? We started using Test Fairy because it just automatically worked right out of the box. Now it doesn't work at all, since it won't compile. See https://github.com/testfairy/testfairy-ane/issues/10

**Comment by Xgamefactory** [comment]
Screencapturing still does not works for android. it just captures native dialogs not adobe air main activity.
